export const LOAD_CONTACTS = "LOAD_CONTACTS";
export const ERROR_HANDLING = "ERROR_HANDLING";
export const ADD_CONTACT = "ADD_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
